[package]
name = "large-example"
version = "0.1.0"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
edition = "2018"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4.11"
stderrlog = { path = "../../" }
